version: 0.2

env:
  variables:
    DB_URL: "postgresql+asyncpg://user:password@db-host/dbname"  # Replace with your actual DB URL

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo Installing dependencies for entrypoint script...
      - pip install poetry
      - poetry install

      - echo Running entrypoint script for database initialization and migrations...
      - chmod +x entrypoint.sh
      - DATABASE_URL=$DB_URL ./entrypoint.sh

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t fastapi-app .
      - docker tag fastapi-app:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fastapi-app:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fastapi-app:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Writing image definitions file...
      - printf '[{"name":"container-name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fastapi-app:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
